# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]
magick = "1.6.0"


# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.19.1"
"rocks-git.nvim" = "1.3.1"
"rocks-config.nvim" = "1.2.3"
"image.nvim" = "1.2.0"
"otter.nvim" = "1.12.1"
nvim-lspconfig = "0.1.7"
vimpeccable = "scm"

[plugins.nvim-cmp]
git = "hrsh7th/nvim-cmp"
rev = "v0.0.1"

[plugins.cmp-nvim-lsp]
git = "hrsh7th/cmp-nvim-lsp"

[plugins.nvim-treesitter]
git = "nvim-treesitter/nvim-treesitter"
rev = "v0.9.2^{}"

[plugins.quarto-nvim]
git = "quarto-dev/quarto-nvim"
rev = "v0.18.2"

[plugins."jupytext.nvim"]
git = "GCBallesteros/jupytext.nvim"

[plugins.molten-nvim]
git = "benlubas/molten-nvim"
rev = "v1.8.0"

